version: '3.7'

services:
  cem-backend:
    image: willmishregistry.azurecr.io/cem-backend
    build: 
      dockerfile: Dockerfile
      context: backend
      platforms:
        - "linux/amd64"
    container_name: cem-backend
    #domainname: campfire-on-the-wall
    ports:
      - "4000:4000"
    networks:
      - cem-app-net
  cem-frontend:
    image: willmishregistry.azurecr.io/cem-frontend
    build: 
      dockerfile: Dockerfile
      context: frontend
      platforms:
        - "linux/amd64"
    container_name: cem-frontend
    #domainname: campfire-on-the-wall
    ports:
      - "8080:3000"
    networks:
      - cem-app-net
  #cem-database:
  #  image: mongo
  #  container_name: cem-database
  #  #domainname: otwock-alert 
  #  restart: always # Restart container on failure
  #  environment:
  #    MONGO_INITDB_ROOT_USERNAME: root
  #    MONGO_INITDB_ROOT_PASSWORD: root
  #  ports:
  #    - 27017:27017 # Map local port to container port
  #  volumes: # Persistent storage
  #    #- ./volumes/database:/data/db # Local volume
  #    - ./config/database/init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro # Setup script run on container start
  #  networks:
  #    - cem-app-net
networks:
  cem-app-net:
    driver: bridge
