version: '3.8'

services:
# --- DATABASE -----------------------------------------
  swp-database:
    image: mongo
    container_name: swp-database
    domainname: sticky-web-platform
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./database/volume:/data/db # Local volume
      #- ./config/database/init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro # Setup script run on container start
    networks:
      - swp-net

# --- WEB SERVER -------------------------------------
  swp-web-server:
    image: nginx:latest
    container_name: swp-web-server
    domainname: sticky-web-platform
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./web_server:/etc/nginx
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - swp-net

# --- STICKY WEB BACKEND -------------------------------
  swp-backend:
    image: swp-backend
    container_name: swp-backend
    domainname: sticky-web-platform
    environment:
      - ASPNETCORE_URLS=http://+:4000
      - ASPNETCORE_ENVIRONMENT=${BACKEND_MODE}
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      # Backend is running in /app directory inside the container,
      # so it will look for the configuration.json file in its parent (according to the appsettings.json file)
      - ./configuration.json:/configuration.json:ro
    networks:
      - swp-net

# --- STICKY WEB FRONTEND ------------------------------
  swp-frontend:
    image: swp-frontend
    container_name: swp-frontend
    domainname: sticky-web-platform
    environment:
      - NEXT_TELEMETRY_DISABLED=1 # Disable Next Js default telemetry collecting: https://nextjs.org/telemetry
      - API_URL=http://swp-backend:4000
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - swp-net
      
# --- CONTAINER NETWORK --------------------------------
networks:
  swp-net:
    driver: bridge
