# For local development: Running backend and server in docker and frontend with "npm run dev" locally

version: '3.8'

services:
  cem-backend:
    image: cem-backend
    container_name: cem-backend
    hostname: cem-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    networks:
      - cem-net
  cem-database:
    image: mongo
    container_name: cem-database
    domainname: city-event-map
    restart: always # Restart container on failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017 # Map local port to container port
    volumes: # Persistent storage
      - ./volumes/database:/data/db # Local volume
      #- ./config/database/init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro # Setup script run on container start
    networks:
      - cem-net
networks:
  cem-net:
    driver: bridge
