version: '3.8'

services:
# --- DATABASE -----------------------------------------
  swf-database:
    image: mongo
    container_name: swf-database
    domainname: sticky-web-framework
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./volumes/database:/data/db # Local volume
      #- ./config/database/init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro # Setup script run on container start
    networks:
      - swf-net

# --- NGINX SERVER -------------------------------------
  swf-nginx:
    image: nginx:latest
    container_name: swf-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./volume/ssl_certificates:/etc/nginx/ssl:ro
    restart: always
    depends_on:
      - swf-backend
      - swf-frontend
    networks:
      - swf-net

# --- STICKY WEB BACKEND -------------------------------
  swf-backend:
    image: swf-backend
    container_name: swf-backend
    hostname: swf-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - swf-database
    networks:
      - swf-net

# --- STICKY WEB FRONTEND ------------------------------
  swf-frontend:
    image: swf-frontend
    container_name: swf-frontend
    domainname: sticky-web-framework
    environment:
      - NEXT_TELEMETRY_DISABLED=1 # Disable Next Js default telemetry collecting: https://nextjs.org/telemetry
      - API_URL=http://swf-backend:4000
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - swf-net
      
# --- CONTAINER NETWORK --------------------------------
networks:
  swf-net:
    driver: bridge
